using RestSharp;
using System;
using System.Collections.Generic;
/* 
 * Vertmarkets Inc. Magazine Store
 *
 * API endpoints to work with magazine data
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
namespace VertMarkets.MagazineStore.API
{
    using System.Collections.ObjectModel;
    using System.Linq;
    using VertMarkets.MagazineStore.API.Model;
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class AnswerApi : IAnswerApi
    {
        private VertMarkets.MagazineStore.API.Client.ExceptionFactory _exceptionFactory = (name, response) => null;
        /// <summary>
        /// Initializes a new instance of the <see cref="AnswerApi"/> class.
        /// </summary>
        /// <returns></returns>
        public AnswerApi(String basePath)
        {
            this.Configuration = new VertMarkets.MagazineStore.API.Client.Configuration { BasePath = basePath };
            ExceptionFactory = VertMarkets.MagazineStore.API.Client.Configuration.DefaultExceptionFactory;
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="AnswerApi"/> class
        /// </summary>
        /// <returns></returns>
        public AnswerApi()
        {
            this.Configuration = VertMarkets.MagazineStore.API.Client.Configuration.Default;
            ExceptionFactory = VertMarkets.MagazineStore.API.Client.Configuration.DefaultExceptionFactory;
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="AnswerApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public AnswerApi(VertMarkets.MagazineStore.API.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = VertMarkets.MagazineStore.API.Client.Configuration.Default;
            else
                this.Configuration = configuration;
            ExceptionFactory = VertMarkets.MagazineStore.API.Client.Configuration.DefaultExceptionFactory;
        }
        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }
        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }
        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public VertMarkets.MagazineStore.API.Client.Configuration Configuration { get; set; }
        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public VertMarkets.MagazineStore.API.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }
        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }
        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }
        /// <summary>
        /// You will be posting your answer to this endpoint. It should be a json object that holds a list of subscribers. 
        /// </summary>
        /// <exception cref="VertMarkets.MagazineStore.API.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="token">This is a string token received from the token endpoint</param>
        /// <param name="body">This is an object with a list of subscriberIds that match the criteria in the exercise (optional)</param>
        /// <returns>ApiResponseAnswerResponse</returns>
        public ApiResponse<AnswerResponse> ApiAnswerByTokenPost(string token, Answer body = null)
        {
            Client.ApiResponse<ApiResponse<AnswerResponse>> localVarResponse = ApiAnswerByTokenPostWithHttpInfo(token, body);
            return localVarResponse.Data;
        }
        /// <summary>
        /// You will be posting your answer to this endpoint. It should be a json object that holds a list of subscribers. 
        /// </summary>
        /// <exception cref="VertMarkets.MagazineStore.API.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="token">This is a string token received from the token endpoint</param>
        /// <param name="body">This is an object with a list of subscriberIds that match the criteria in the exercise (optional)</param>
        /// <returns>ApiResponse of ApiResponseAnswerResponse</returns>
        public Client.ApiResponse<ApiResponse<AnswerResponse>> ApiAnswerByTokenPostWithHttpInfo(string token, Answer body = null)
        {
            // verify the required parameter 'token' is set
            if (token == null)
                throw new Client.ApiException(400, "Missing required parameter 'token' when calling AnswerApi->ApiAnswerByTokenPost");
            var localVarPath = "/api/answer/{token}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;
            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json-patch+json",
                "application/json",
                "text/json",
                "application/_*+json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);
            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);
            if (token != null) localVarPathParams.Add("token", this.Configuration.ApiClient.ParameterToString(token)); // path parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }
            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse)this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);
            int localVarStatusCode = (int)localVarResponse.StatusCode;
            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ApiAnswerByTokenPost", localVarResponse);
                if (exception != null) throw exception;
            }
            return new Client.ApiResponse<ApiResponse<AnswerResponse>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (ApiResponse<AnswerResponse>)this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(ApiResponse<AnswerResponse>)));
        }
        /// <summary>
        /// You will be posting your answer to this endpoint. It should be a json object that holds a list of subscribers. 
        /// </summary>
        /// <exception cref="VertMarkets.MagazineStore.API.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="token">This is a string token received from the token endpoint</param>
        /// <param name="body">This is an object with a list of subscriberIds that match the criteria in the exercise (optional)</param>
        /// <returns>Task of ApiResponseAnswerResponse</returns>
        public async System.Threading.Tasks.Task<ApiResponse<AnswerResponse>> ApiAnswerByTokenPostAsync(string token, Answer body = null)
        {
            Client.ApiResponse<ApiResponse<AnswerResponse>> localVarResponse = await ApiAnswerByTokenPostAsyncWithHttpInfo(token, body);
            return localVarResponse.Data;
        }
        /// <summary>
        /// You will be posting your answer to this endpoint. It should be a json object that holds a list of subscribers. 
        /// </summary>
        /// <exception cref="VertMarkets.MagazineStore.API.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="token">This is a string token received from the token endpoint</param>
        /// <param name="body">This is an object with a list of subscriberIds that match the criteria in the exercise (optional)</param>
        /// <returns>Task of ApiResponse (ApiResponseAnswerResponse)</returns>
        public async System.Threading.Tasks.Task<Client.ApiResponse<ApiResponse<AnswerResponse>>> ApiAnswerByTokenPostAsyncWithHttpInfo(string token, Answer body = null)
        {
            // verify the required parameter 'token' is set
            if (token == null)
                throw new Client.ApiException(400, "Missing required parameter 'token' when calling AnswerApi->ApiAnswerByTokenPost");
            var localVarPath = "/api/answer/{token}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;
            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json-patch+json",
                "application/json",
                "text/json",
                "application/_*+json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);
            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);
            if (token != null) localVarPathParams.Add("token", this.Configuration.ApiClient.ParameterToString(token)); // path parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }
            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse)await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);
            int localVarStatusCode = (int)localVarResponse.StatusCode;
            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ApiAnswerByTokenPost", localVarResponse);
                if (exception != null) throw exception;
            }
            return new Client.ApiResponse<ApiResponse<AnswerResponse>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (ApiResponse<AnswerResponse>)this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(ApiResponse<AnswerResponse>)));
        }
    }
}
